import identity from "../brand/identity.json";
import { escapeHtml } from "./export.js";

export type ConnectionPageState = "connected" | "identity" | "error";
/** This page is self-contained: OAuth codes and account information never enter its markup. */
export function connectionPage(state: ConnectionPageState, provider: "chatgpt" | "openrouter", returnUrl?: string, nonce?: string) {
  const name = escapeHtml(identity.name), enabled = state === "connected", failed = state === "error";
  let safeReturn = "";
  if (returnUrl) {
    const url = new URL(returnUrl);
    if (url.protocol === "http:" && ["127.0.0.1", "localhost", "[::1]"].includes(url.hostname) && !url.username && !url.password)
      safeReturn = escapeHtml(url.origin + "/");
  }
  const title = failed ? "Let's reconnect" : enabled ? provider === "chatgpt" ? "ChatGPT connected" : "OpenRouter connected" : "One more step for your ChatGPT plan";
  const description = failed ? "This connection could not be completed. Return to your workspace and start a fresh sign-in." : enabled ?
    provider === "chatgpt" ? "Your original workspace updates automatically. Return there to continue with your ChatGPT plan." : "OpenRouter is connected. Your workspace can now use the models available through your account." :
    "You're signed in, but ChatGPT plan usage wasn't enabled. Return to Connections to review permissions before running AI work.";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${enabled ? "Connected" : failed ? "Connection incomplete" : "Signed in"} | ${name}</title><style>
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:#f7f9fc;color:#0f172a;font:15px/1.65 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;display:grid;place-items:center;padding:36px 20px}.frame{width:min(100%,530px)}.brand{display:flex;align-items:center;gap:10px;font-weight:650;font-size:20px;margin:0 0 30px 6px;letter-spacing:-.5px}.brand svg{width:34px;height:34px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:42px;box-shadow:0 12px 40px #0f172a06}.status{display:grid;place-items:center;width:52px;height:52px;border-radius:16px;background:${failed ? "#fff7ed" : "#eff6ff"};color:${failed ? "#9a3412" : identity.primary};margin-bottom:26px}.status svg{width:26px;height:26px}h1{font-size:30px;line-height:1.2;letter-spacing:-1px;font-weight:650;margin:0 0 18px}p{margin:0;color:#64748b}.detail{margin:28px 0;padding:19px 0;border-top:1px solid #eef2f6;border-bottom:1px solid #eef2f6;display:flex;gap:12px;align-items:flex-start}.detail svg{flex:none;width:19px;height:19px;color:#64748b;margin-top:3px}.detail strong{display:block;font-size:13px;font-weight:600;color:#334155}.detail p{font-size:12px;margin-top:4px}.primary{display:flex;align-items:center;justify-content:center;gap:10px;border-radius:9px;padding:12px 16px;background:${identity.primary};color:white;text-decoration:none;font-size:14px;font-weight:600;border:0;width:100%;cursor:pointer;font-family:inherit}.primary svg{width:17px;height:17px}.primary:focus-visible,a:focus-visible{outline:3px solid #93c5fd;outline-offset:4px}.foot{font-size:12px;text-align:center;margin:20px 0 0}.foot a{color:#475569}.return-link{display:flex;align-items:center;justify-content:center;gap:7px;color:#475569;font-size:12px;text-decoration:none;margin-top:14px}.return-link svg{width:14px;height:14px}.return-link:hover{color:#1166df;text-decoration:underline}.hint{text-align:center;font-size:12px;margin:24px 0 0;color:#64748b}@media(max-width:480px){.card{padding:28px}h1{font-size:26px}.brand{margin-bottom:22px}}
    </style></head><body><main class="frame"><div class="brand"><svg viewBox="0 0 64 64" aria-hidden="true"><path fill="${identity.primary}" fill-rule="evenodd" d="${identity.symbolPath}"/></svg>${name}</div><section class="card"><div class="status"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${failed ? '<path d="M12 8v5m0 4h.01M10 3 2 18a2 2 0 0 0 2 3h16a2 2 0 0 0 2-3L14 3a2 2 0 0 0-4 0Z"/>' : '<path d="m5 12 4 4L19 6"/>'}</svg></div><h1>${title}</h1><p>${description}</p><div class="detail"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-11V5l-8-3-8 3v6c0 7 8 11 8 11Z"/><path d="m9 12 2 2 4-4"/></svg><div><strong>${failed ? "Your local work is safe" : "Your connection stays on this device"}</strong><p>${failed ? "Projects, evidence and drafts are preserved." : "Credentials are protected locally and excluded from project exports."}</p></div></div>${enabled && nonce ? `<button class="primary" id="close-connection">Close sign-in window</button><p class="hint" id="return-hint">Continue in the window where you started.</p>` : ""}${safeReturn ? `<a class="${enabled && nonce ? "return-link" : "primary"}" href="${safeReturn}">${enabled && nonce ? "Open workspace if you closed it" : "Return to " + name}<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg></a>` : `<p>Return to ${name} to continue.</p>`}${enabled && provider === "chatgpt" ? '<p class="foot">ChatGPT plan limits apply. <a href="https://chatgpt.com/settings/usage" target="_blank" rel="noreferrer">Manage usage</a></p>' : enabled ? '<p class="foot">Model usage is billed to your OpenRouter account.</p>' : ""}</section><p class="hint">You can close this window after returning to the application.</p></main>${nonce ? `<script nonce="${nonce}">document.getElementById("close-connection")?.addEventListener("click",function(){window.close();document.getElementById("return-hint").textContent="Switch back to your original workspace. You can close this tab.";});</script>` : ""}</body></html>`;
}
