import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { start } from '../server/main.js';
import { jobInput, projectInput, type Observation } from '../server/contracts.js';
import { navigate } from './ui-navigation.js';

const directory = mkdtempSync(join(tmpdir(), 'opengeo-recheck-ui-'));
const runtime = await start({ directory, port: 0, protector: { encrypt: text => Buffer.from(text), decrypt: bytes => bytes.toString() } });
const browser = await chromium.launch({ ...(process.env.OPENGEO_TEST_BROWSER ? { executablePath: process.env.OPENGEO_TEST_BROWSER } : { channel: 'chrome' }), headless: true });
const originalFetch = globalThis.fetch;
let available = ['new-default', 'previous-model'];
globalThis.fetch = (async url => {
  assert.ok(String(url).endsWith('/models'), 'Only catalog discovery is permitted');
  return new Response(JSON.stringify({ models: available.map(slug => ({ slug, display_name: slug, visibility: 'list', context_window: 32768 })) }), { headers: { 'Content-Type': 'application/json' } });
}) as typeof fetch;
try {
  await runtime.runner.stop(); runtime.scheduler.stop();
  const project = runtime.store.createProject(projectInput.parse({ domain: 'example.com', brand: 'Example', prompts: ['Where can I find a documentation example?'] }));
  runtime.store.set('onboarding', { completed: true });
  runtime.runner.providers.vault.set('chatgpt', { active: 'fixture', profiles: [{ id: 'fixture', access_token: 'synthetic-access', expiresAt: Date.now() + 3600000, scopes: ['chatgpt.tokens.use.direct'] }] });
  const baseline = runtime.store.enqueue(jobInput.parse({ projectId: project.id, kind: 'measure', provider: 'chatgpt', model: 'previous-model', webSearch: false }), randomUUID());
  const observation: Observation = { id: randomUUID(), projectId: project.id, jobId: baseline.id, provider: 'chatgpt', model: 'previous-model', platform: 'chat_gpt', locale: 'en-US', prompt: project.prompts[0], answer: 'Example provides documentation examples.', citations: [], surface: 'api', mentioned: true, cited: false, costUsd: 0, observedAt: new Date().toISOString() };
  runtime.store.put('observation', project.id, baseline.id, observation);
  runtime.store.updateJob(baseline.id, { status: 'completed', requestedAnswers: 1 });
  const page = await browser.newPage({ viewport: { width: 1360, height: 900 } });
  page.setDefaultTimeout(15000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:' + (runtime.app.server.address() as any).port);
  await navigate(page, 'Visibility');
  await page.getByRole('button', { name: 'Recheck', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Recheck AI visibility', exact: true });
  await dialog.getByRole('button', { name: 'Model', exact: true }).getByText('previous-model', { exact: true }).waitFor();
  assert.equal(await dialog.getByRole('checkbox', { name: /Search the web for this check/ }).isChecked(), false);
  await dialog.getByRole('button', { name: 'Recheck visibility', exact: true }).click();
  await dialog.waitFor({ state: 'hidden' });
  const accepted = runtime.store.jobs(project.id).find(job => job.kind === 'recheck')!;
  assert.equal(accepted.provider, baseline.provider);
  assert.equal(accepted.model, baseline.model);
  assert.equal(accepted.platform, baseline.platform);
  assert.equal(accepted.webSearch, baseline.webSearch);
  assert.equal(accepted.maxCostUsd, 0);
  await page.locator('.metric').filter({ hasText: 'Answers remaining' }).getByText('Starting', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Recheck', exact: true }).isDisabled(), true);
  assert.equal(await page.locator('.prompt-table').getByText('1 remaining', { exact: true }).count(), 0);
  runtime.store.updateJob(accepted.id, { status: 'cancelled' });
  available = ['new-default'];
  await page.reload(); await navigate(page, 'Visibility');
  await page.getByRole('button', { name: 'Recheck', exact: true }).click();
  await dialog.getByRole('button', { name: 'Model', exact: true }).getByText('Choose a model', { exact: true }).waitFor();
  assert.equal(await dialog.getByRole('button', { name: 'Recheck visibility', exact: true }).isDisabled(), true);
  assert.equal(runtime.store.jobs(project.id).filter(job => job.kind === 'recheck').length, 1);
  await dialog.getByRole('button', { name: 'Model', exact: true }).click();
  await page.getByRole('option', { name: /new-default/ }).click();
  assert.equal(await dialog.getByRole('button', { name: 'Recheck visibility', exact: true }).isEnabled(), true);
  await dialog.getByText('Different answer settings start a separate comparison.', { exact: true }).waitFor();
  await dialog.getByRole('button', { name: 'Close dialog', exact: true }).click();
  runtime.runner.providers.vault.remove('chatgpt');
  runtime.runner.providers.vault.set('console', { key: 'synthetic-console-key' });
  await page.reload(); await navigate(page, 'Visibility');
  await page.getByRole('button', { name: 'Recheck', exact: true }).click();
  await dialog.getByText('The previous connection is unavailable. Reconnect it in Settings or choose another connection.', { exact: true }).waitFor();
  await dialog.getByRole('button', { name: 'Connection', exact: true }).getByText('Choose a connected provider', { exact: true }).waitFor();
  assert.equal(await dialog.getByRole('button', { name: 'Recheck visibility', exact: true }).isDisabled(), true);
  assert.equal(runtime.store.jobs(project.id).filter(job => job.kind === 'recheck').length, 1);
  assert.deepEqual(errors, []);
  console.log('Browser verified: previous model and retrieval settings retained, unavailable models require explicit choice, no silent provider fallback, queued checks do not relabel previous results. No inference or paid provider requests.');
} finally {
  globalThis.fetch = originalFetch;
  await browser.close(); await runtime.app.close();
  rmSync(directory, { recursive: true, force: true });
}
