import assert from "node:assert/strict";
import { navigate } from "./ui-navigation.js";
import { mkdtempSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { chromium } from "playwright";
import { start } from "../server/main.js";
import { parsePage } from '../server/audit.js';
import type { Observation } from '../server/contracts.js';
const directory = mkdtempSync(join(tmpdir(), "opengeo-ui-review-"));
const screenshots = join(process.env.LOCALAPPDATA ?? tmpdir(), 'OpenGEO', 'workflow-ux-review');
mkdirSync(screenshots, { recursive: true });
const runtime = await start({ directory, port: 0, protector: { encrypt: (text) => Buffer.from(text), decrypt: (bytes) => bytes.toString() } });
const browser = await chromium.launch({ ...(process.env.OPENGEO_TEST_BROWSER ? { executablePath: process.env.OPENGEO_TEST_BROWSER } : { channel: 'chrome' }), headless: true });
try {
  await runtime.runner.stop(); runtime.scheduler.stop();
  const page = await browser.newPage({ viewport: { width: 1360, height: 960 } });
  const failures: string[] = []; page.on("pageerror", (error) => failures.push(error.message));
  await page.goto("http://127.0.0.1:" + (runtime.app.server.address() as any).port);
  await page.getByRole("heading", { name: "Power your AI visibility workspace", exact: true }).waitFor();
  assert.equal(await page.getByRole("navigation", { name: "Main navigation" }).count(), 0);
  assert.equal(await page.getByRole("button", { name: "Continue", exact: true }).isDisabled(), true);
  await page.getByRole("button", { name: "Use local audits only", exact: true }).click();
  await page.getByRole("heading", { name: "Which website are you improving?", exact: true }).waitFor();
  assert.deepEqual(await page.getByRole("list", { name: "Setup progress" }).locator("strong").allTextContents(), ["Connection", "Website", "Review"]);
  await page.getByRole("textbox", { name: "Website", exact: true }).fill("127.0.0.1");
  await page.getByRole("textbox", { name: "Brand name", exact: true }).fill("Example");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByText("Review the highlighted fields.", { exact: true }).waitFor();
  assert.equal(await page.getByRole("textbox", { name: "Website", exact: true }).getAttribute("aria-invalid"), "true");
  assert.equal(runtime.store.projects().length, 0);
  await page.getByRole("button", { name: /^Website: Enter a public/ }).click();
  assert.equal(await page.getByRole("textbox", { name: "Website", exact: true }).evaluate(element => element === document.activeElement), true);
  await page.getByRole("textbox", { name: "Website", exact: true }).fill("example.com");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("heading", { name: "Ready for your first check?", exact: true }).waitFor();
  await page.reload();
  await page.getByRole("heading", { name: "Ready for your first check?", exact: true }).waitFor();
  assert.equal(runtime.store.projects().length, 1, "Reloading setup keeps the same website");
  await page.getByRole("button", { name: "Open workspace & audit", exact: true }).click();
  await page.getByRole("heading", { name: "Overview", exact: true }).waitFor();
  assert.equal(runtime.store.jobs().length, 1);
  assert.equal(runtime.store.jobs()[0].provider, undefined);
  assert.equal(runtime.store.jobs()[0].maxCostUsd, 0);
  const activeNavigationColors = await page.evaluate(() => {
    const style = getComputedStyle(document.querySelector('nav button[aria-current="page"]')!);
    return { foreground: style.color, background: style.backgroundColor };
  });
  const luminance = (color: string) => {
    const [r, g, b] = color.match(/[\d.]+/g)!.slice(0, 3).map(Number).map(value => {
      const channel = value / 255; return channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4;
    });
    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
  };
  const foreground = luminance(activeNavigationColors.foreground), background = luminance(activeNavigationColors.background);
  const activeNavigationContrast = (Math.max(foreground, background) + 0.05) / (Math.min(foreground, background) + 0.05);
  assert.ok(activeNavigationContrast >= 4.5, "Active navigation text meets the normal-text contrast threshold");
  assert.equal(await page.getByRole("button", { name: "Audit queued", exact: true }).isDisabled(), true);
  await page.getByRole("heading", { name: "Your site audit is queued", exact: true }).waitFor();
  await page.route("**/api/projects/*/workspace", route => route.abort("failed"));
  await page.getByRole("button", { name: "Refresh workspace", exact: true }).click();
  const staleNotice = page.getByRole("alert").filter({ hasText: "Could not refresh your workspace." });
  await staleNotice.waitFor();
  assert.match(await staleNotice.textContent() ?? "", /Showing the last loaded results/);
  await page.getByRole("heading", { name: "Your site audit is queued", exact: true }).waitFor();
  await page.unroute("**/api/projects/*/workspace");
  await staleNotice.getByRole("button", { name: "Try again", exact: true }).click();
  await staleNotice.waitFor({ state: "detached" });
  let releaseOldRefresh!: () => void, receivedOldRefresh!: () => void;
  const oldRefreshReceived = new Promise<void>(resolve => { receivedOldRefresh = resolve; });
  const oldRefreshRelease = new Promise<void>(resolve => { releaseOldRefresh = resolve; });
  let captured = false;
  await page.route("**/api/projects/*/workspace", async route => {
    if (captured) { await route.continue(); return; }
    captured = true;
    const response = await route.fetch();
    receivedOldRefresh();
    await oldRefreshRelease;
    await route.fulfill({ response });
  });
  await page.getByRole("button", { name: "Refresh workspace", exact: true }).click();
  await oldRefreshReceived;
  runtime.store.updateJob(runtime.store.jobs()[0].id, { progress: "A newer audit checkpoint" });
  await page.getByText("A newer audit checkpoint", { exact: true }).waitFor();
  const oldRefreshCompleted = page.waitForResponse(response => response.url().endsWith("/workspace"));
  releaseOldRefresh();
  await oldRefreshCompleted;
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  assert.equal(await page.getByText("A newer audit checkpoint", { exact: true }).count(), 1, "An older response cannot replace newer evidence");
  await page.unroute("**/api/projects/*/workspace");
  assert.equal(await page.getByRole("button", { name: /Recheck the same questions/ }).isDisabled(), true);
  await page.getByRole("button", { name: "Website", exact: true }).click();
  await page.getByRole("combobox", { name: "Search website", exact: true }).fill("example");
  await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter");
  assert.equal(await page.getByRole("listbox").count(), 0);
  await page.getByRole("button", { name: "Website", exact: true }).click();
  await page.keyboard.press("Tab");
  assert.equal(await page.getByRole("listbox").count(), 0);
  assert.equal(await page.evaluate(() => document.activeElement !== document.body), true);
  await page.getByRole("button", { name: "Visibility", exact: true }).click();
  await page.getByRole("button", { name: "Add a question", exact: true }).click();
  await page.getByRole("textbox", { name: "Question 1", exact: true }).fill("Q");
  await page.getByText("Brand, language and competitors", { exact: true }).click();
  await page.getByLabel("Other names for your brand", { exact: true }).fill("x");
  await page.getByText("Brand, language and competitors", { exact: true }).click();
  await page.getByRole("button", { name: "Save questions", exact: true }).click();
  await page.getByText("Review the highlighted fields.", { exact: true }).waitFor();
  assert.equal(await page.getByRole("textbox", { name: "Question 1", exact: true }).getAttribute("aria-invalid"), "true");
  assert.equal(await page.getByRole("textbox", { name: "Question 1", exact: true }).textContent(), "Q");
  await page.getByRole("button", { name: /^Brand aliases:/ }).click();
  assert.equal(await page.getByLabel("Other names for your brand", { exact: true }).evaluate(element => element === document.activeElement), true);
  assert.equal(await page.getByLabel("Other names for your brand", { exact: true }).evaluate(element => element.getAttribute("aria-describedby")?.split(" ").every(id => !!document.getElementById(id))), true);
  await page.getByLabel("Other names for your brand", { exact: true }).fill("");
  await page.getByRole("textbox", { name: "Question 1", exact: true }).fill("What is an example domain?");
  await page.getByRole("button", { name: "Save questions", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Questions and website details saved." }).waitFor();
  assert.equal(await page.getByRole("textbox", { name: "Question 1", exact: true }).getAttribute("aria-invalid"), null);
  assert.equal(await page.getByRole("button", { name: "Check visibility", exact: true }).count(), 0);
  await page.getByRole("button", { name: "Connect for AI checks", exact: true }).click();
  await page.getByRole("heading", { name: "Your connections" }).waitFor();
  assert.equal(await page.getByRole("tab", { name: "Connections", exact: true }).getAttribute("aria-selected"), "true");
  assert.deepEqual(await page.locator(".provider-card h2").allTextContents(), ["ChatGPT", "SurfacedBy API", "DataForSEO", "OpenRouter"]);
  await page.getByRole("tab", { name: "Schedules", exact: true }).click();
  await page.getByRole("button", { name: "Add schedule", exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "Schedule connection", exact: true }).count(), 0);
  assert.equal(await page.locator('input[name="project"]').inputValue(), runtime.store.projects()[0].id);
  await page.getByRole("button", { name: "Schedule frequency", exact: true }).click();
  await page.getByRole("option", { name: "Daily", exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "Schedule day", exact: true }).count(), 0);
  let scheduleRequestKey = "";
  await page.route("**/api/schedules", async route => {
    if (route.request().method() !== "POST") { await route.continue(); return; }
    scheduleRequestKey = route.request().headers()["idempotency-key"];
    assert.equal((await route.fetch()).ok(), true);
    await route.abort("failed");
  });
  await page.getByRole("button", { name: "Save schedule", exact: true }).click();
  await page.getByText("The workspace did not confirm this schedule. Check your schedules or retry with the same settings.", { exact: true }).waitFor();
  assert.equal(runtime.scheduler.list().length, 1);
  assert.equal(await page.locator('main > [role="alert"]').count(), 0);
  await page.unroute("**/api/schedules");
  let scheduleRetryKey = "";
  await page.route("**/api/schedules", async route => {
    if (route.request().method() === "POST") scheduleRetryKey = route.request().headers()["idempotency-key"];
    await route.continue();
  });
  await page.getByRole("button", { name: "Save schedule", exact: true }).click();
  await page.getByText("Schedule saved.", { exact: true }).waitFor();
  assert.equal(scheduleRetryKey, scheduleRequestKey);
  assert.equal(runtime.scheduler.list().length, 1);
  await page.unroute("**/api/schedules");
  await page.getByRole("button", { name: "Remove schedule for example.com" }).waitFor();
  const schedule = runtime.scheduler.list()[0]; assert.equal(schedule.job.kind, "audit"); assert.equal(schedule.job.provider, undefined); assert.equal(schedule.frequency, "daily"); assert.equal(schedule.job.maxCostUsd, 0);
  await page.getByRole("button", { name: "Add schedule", exact: true }).click();
  await page.getByRole("button", { name: "Scheduled workflow", exact: true }).click();
  await page.getByRole("option", { name: "Visibility recheck", exact: true }).click();
  await page.getByText("Connect a provider in Connections before scheduling AI work.", { exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Schedule connection", exact: true }).count(), 0);
  assert.equal(await page.getByRole("button", { name: "Save schedule", exact: true }).isDisabled(), true);
  await page.getByRole("button", { name: "Content", exact: true }).click();
  await page.getByRole("heading", { name: "Content", exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Actions", exact: true }).count(), 0);
  // Explicit synthetic user records exercise the real editor and SQLite save path.
  const projectId = runtime.store.projects()[0].id, jobId = runtime.store.jobs()[0].id;
  const draft = { id: randomUUID(), topic: "Synthetic documentation draft", markdown: "# Draft\n\nOriginal text.", brief: "A short brief.", createdAt: new Date().toISOString(), locale: "en-US", reviewCurrent: true, sourceEvidence: [], review: { issues: [{ claim: "Synthetic disputed claim", reason: "Needs supporting evidence", evidenceIds: [] }] } };
  runtime.store.put("content", projectId, jobId, draft);
  runtime.store.put("content", projectId, jobId, { ...draft, id: randomUUID(), topic: "Another synthetic draft" });
  await page.getByRole("button", { name: "Refresh workspace", exact: true }).click();
  await page.getByRole("button", { name: "Open draft: Synthetic documentation draft", exact: true }).click();
  await page.getByText("1 claim needs review", { exact: true }).waitFor();
  assert.equal(await page.locator(".draft-review").getAttribute("open"), null);
  await page.locator('.draft-review summary').focus();
  await page.keyboard.press('Enter');
  await page.getByText('Synthetic disputed claim', { exact: true }).waitFor();
  assert.equal(await page.locator('.draft-review').getAttribute('open'), '');
  await page.keyboard.press('Enter');
  await page.getByRole("button", { name: "Edit Markdown", exact: true }).click();
  await page.getByRole("textbox", { name: "Draft for " + draft.topic }).fill("# Draft\n\nSaved changes.");
  await page.getByRole("button", { name: "Overview", exact: true }).click();
  await page.getByRole("heading", { name: "Save your changes?", exact: true }).waitFor();
  await page.getByRole("button", { name: "Keep editing", exact: true }).click();
  assert.equal(await page.getByRole("textbox", { name: "Draft for " + draft.topic }).inputValue(), "# Draft\n\nSaved changes.");
  await page.getByRole("button", { name: "Overview", exact: true }).click();
  await page.getByRole("button", { name: "Save and continue", exact: true }).click();
  await page.getByRole("heading", { name: "Overview", exact: true }).waitFor();
  const stored = runtime.store.artifacts<any>(projectId, "content").find((entry) => entry.id === draft.id);
  assert.equal(stored.markdown, "# Draft\n\nSaved changes."); assert.equal(stored.reviewCurrent, false);
  assert.equal(await page.getByRole("button", { name: /Make an evidence-based improvement/ }).locator(".step.done").count(), 0);
  await page.getByRole("button", { name: "Content", exact: true }).click();
  await page.getByRole("button", { name: "Open draft: Synthetic documentation draft", exact: true }).click();
  await page.getByRole("button", { name: "Edit Markdown", exact: true }).click();
  await page.getByRole("textbox", { name: "Draft for " + draft.topic }).fill("Unsaved text to discard.");
  await page.getByRole("button", { name: "All drafts", exact: true }).click();
  await page.getByRole("button", { name: "Discard changes", exact: true }).click();
  await page.getByRole("button", { name: "Open draft: Another synthetic draft", exact: true }).click();
  await page.getByRole("heading", { name: "Another synthetic draft", exact: true }).waitFor();
  await page.screenshot({ path: join(screenshots, 'content-desktop-test-data.png') });
  assert.equal(runtime.store.artifacts<any>(projectId, "content").find((entry) => entry.id === draft.id).markdown, "# Draft\n\nSaved changes.");
  const measurement = runtime.store.enqueue({ projectId, kind: "measure", provider: "chatgpt", model: "test-model", maxCostUsd: 0 } as any, "synthetic-ui-measurement");
  runtime.store.updateJob(measurement.id, { status: "completed" });
  const observation: Observation = { id: randomUUID(), projectId, jobId: measurement.id, locale: 'en-US', costUsd: 0, surface: 'api', prompt: "Synthetic question", answer: "Synthetic answer text.", platform: "chat_gpt", provider: "chatgpt", model: "test-model", observedAt: new Date().toISOString(), citations: [], retrieval: "model_only", mentioned: false, cited: false };
  runtime.store.put("observation", projectId, measurement.id, observation);
  await page.getByRole("button", { name: "Refresh workspace", exact: true }).click();
  await page.getByRole("button", { name: "Responses", exact: true }).click();
  await page.locator(".answer-meta").getByText("ChatGPT", { exact: true }).waitFor();
  await page.getByRole("textbox", { name: "Search answers", exact: true }).fill("unmatched phrase");
  await page.getByRole("heading", { name: "No matching answers", exact: true }).waitFor();
  await page.getByRole("textbox", { name: "Search answers", exact: true }).fill("");
  await page.getByRole("heading", { name: "Synthetic question", exact: true }).waitFor();
  runtime.store.put('page', projectId, jobId, parsePage('https://example.com/', 200, '<title>Example domain</title><h1>Example domain</h1><p>A synthetic audit result for interface verification.</p>'));
  runtime.store.updateJob(jobId, { status: 'completed' });
  const diagnosis = runtime.store.enqueue({ projectId, kind: 'diagnose', provider: 'chatgpt', maxCostUsd: 0 } as any, 'synthetic-ui-diagnosis');
  runtime.store.updateJob(diagnosis.id, { status: 'paused', error: 'interrupted', progress: 'Synthetic request interrupted.' });
  await page.getByRole('button', { name: 'Refresh workspace', exact: true }).click();
  await navigate(page, 'Overview');
  await page.getByRole('button', { name: 'Review paused analysis', exact: true }).click();
  await page.getByRole('heading', { name: 'Continue your saved analysis', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Analyze evidence', exact: true }).count(), 0);
  assert.equal(runtime.store.jobs(projectId).filter(job => job.kind === 'diagnose').length, 1);
  runtime.store.updateJob(diagnosis.id, { status: 'completed', result: { measurementJobId: measurement.id } });
  const finding = { id: randomUUID(), projectId, jobId: diagnosis.id, title: 'Explain the example domain purpose', description: 'A synthetic recommendation grounded in the example domain page.', priority: 'medium', targetUrl: 'https://example.com/', evidenceIds: [], steps: ['Review the existing explanation before editing.'], confidence: 'inferred', status: 'open', kind: 'analysis' };
  runtime.store.put('finding', projectId, diagnosis.id, finding);
  runtime.store.put('finding', projectId, measurement.id, { ...finding, id: randomUUID(), jobId: measurement.id, title: 'Legacy missing mention signal', kind: 'visibility' });
  runtime.store.put('finding', projectId, jobId, { ...finding, id: randomUUID(), jobId, title: 'Synthetic technical page check', kind: 'heading' });
  await page.getByRole('button', { name: 'Refresh workspace', exact: true }).click();
  await navigate(page, 'Opportunities');
  await page.locator('.improvement-group > summary').getByText(finding.title, { exact: true }).waitFor();
  assert.equal(await page.getByText('Legacy missing mention signal', { exact: true }).count(), 0);
  assert.equal(await page.getByText('Synthetic technical page check', { exact: true }).count(), 0);
  await page.locator('.improvement-group > summary').click();
  await page.screenshot({ path: join(screenshots, 'opportunities-desktop-test-data.png') });
  await page.getByRole('button', { name: 'Draft page copy', exact: true }).click();
  await page.getByRole('heading', { name: 'Connect a provider to continue', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.getByRole('heading', { name: 'Opportunities', exact: true }).waitFor();
  assert.equal(runtime.store.artifacts(projectId, 'content').length, 2);
  await navigate(page, 'Site Audit');
  await page.getByText('Synthetic technical page check', { exact: true }).waitFor();
  await page.screenshot({ path: join(screenshots, 'site-audit-desktop-test-data.png') });
  assert.equal(await page.getByText(finding.title, { exact: true }).count(), 0);
  assert.equal(await page.locator("select").count(), 0);
  assert.equal(await page.getByRole("alert").count(), 0);
  assert.deepEqual(failures, []);
  await page.setViewportSize({ width: 390, height: 780 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.getByRole("button", { name: "Mobile website", exact: true }).click();
  await page.getByRole("option", { name: /example.com/ }).click();
  await navigate(page, "Settings");
  await page.getByRole("heading", { name: "Your connections" }).waitFor();
  assert.equal(await page.evaluate(() => document.querySelector('main')!.scrollWidth > document.querySelector('main')!.clientWidth), false);
  console.log("UI verified: connection-first setup, local-only path, restart recovery, one free audit, contextual actions, keyboard selectors, provider order, schedules, draft review, unsaved-edit recovery and mobile layout.");
} finally { await browser.close(); await runtime.app.close(); rmSync(directory, { recursive: true, force: true }); }
