import { chromium } from "playwright";
import { mkdtempSync, mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { start } from "../server/main.js";
const directory = mkdtempSync(join(tmpdir(), "opengeo-ux-runtime-"));
const output = join(process.env.LOCALAPPDATA ?? tmpdir(), "OpenGEO", "ux-review");
mkdirSync(output, { recursive: true });
const runtime = await start({ directory, port: 0, protector: { encrypt: (text) => Buffer.from(text), decrypt: (bytes) => bytes.toString() } });
const browser = await chromium.launch({ channel: "chrome", headless: true });
try {
  runtime.scheduler.stop(); await runtime.runner.stop();
  const page = await browser.newPage({ viewport: { width: 1320, height: 860 }, deviceScaleFactor: 2 });
  await page.goto("http://127.0.0.1:" + (runtime.app.server.address() as any).port);
  await page.getByRole("heading", { name: "Power your AI visibility workspace", exact: true }).waitFor();
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: join(output, "after-first-launch.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 780 });
  await page.screenshot({ path: join(output, "after-first-launch-mobile.png"), fullPage: true });
  await page.getByRole("button", { name: "Use local audits only", exact: true }).click();
  await page.getByRole("textbox", { name: "Website", exact: true }).fill("example.com");
  await page.getByRole("textbox", { name: "Brand name", exact: true }).fill("Example Domain");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.screenshot({ path: join(output, "after-setup-review-mobile.png"), fullPage: true });
  await page.getByRole("button", { name: "Open workspace & audit", exact: true }).click();
  await page.getByRole("heading", { name: "Overview", exact: true }).waitFor();
  await runtime.runner.tick();
  await page.getByRole("button", { name: "Refresh workspace", exact: true }).click();
  await page.setViewportSize({ width: 1320, height: 860 });
  await page.screenshot({ path: join(output, "after-first-audit.png") });
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await page.getByRole("heading", { name: "Your connections" }).waitFor();
  await page.screenshot({ path: join(output, "after-settings.png") });
  await page.setViewportSize({ width: 760, height: 600 });
  await page.locator(".shell").screenshot({ path: join(output, "after-settings-small.png") });
  await page.setViewportSize({ width: 390, height: 780 });
  await page.screenshot({ path: join(output, "after-settings-mobile.png") });
  console.log(JSON.stringify({ output, horizontalOverflow: await page.evaluate(() => document.documentElement.scrollWidth > innerWidth) }));
} finally { await browser.close(); await runtime.app.close(); rmSync(directory, { recursive: true, force: true }); }
